sudo: false

language: python
python:
    - "3.6"

install:
    - pip install -e .
    - pip install pycodestyle flake8 codecov
script:
    - python setup.py test
    - pycodestyle torch_complex tests
    - flake8 torch_complex tests
after_success:
    - codecov
