sudo: false

language: python
python:
    - "3.5"
    - "3.6"

install:
    - python --version
    - pip install torch
    - pip install -e .
    - pip install --upgrade pycodestyle flake8 codecov
    - pycodestyle --version
script:
    - python setup.py test
    - pycodestyle torch_complex tests
    - flake8 torch_complex tests
after_success:
    - codecov
